language: c
sudo: required
install: "wget 'https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-ocaml.sh'; bash -ex .travis-ocaml.sh"
script:
  - opam install -y ounit omake
  - export PATH=$HOME/.opam/4.01.0/bin:$PATH
  - echo $PATH
  - omake test
  - sh test/executable/test.sh
env:
  - OCAML_VERSION=4.01
os:
  - linux
